# Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-red-glade-aqeldwos-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_vd0CRMt6WOIo}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# JWT Settings
# Secret must be at least 256-bit (64 hex characters)
quiznova.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
quiznova.jwt.expiration=86400000

# Admin Secret Key
quiznova.admin.secret-key=QUIZNOVA2026

